services:

  db:
    image: postgres:16.3
    container_name: $DB_CONTAINER_NAME
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 3s
      timeout: 5s
      retries: 10

  auth-service:
    build: ./auth-service
    container_name: $WEB_APP_CONTAINER_NAME
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${WEB_APP_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_PASSWORD: $POSTGRES_PASSWORD
      DB_USER: $POSTGRES_USER
      DB_NAME: $POSTGRES_DB
      DB_HOST: $DB_CONTAINER_NAME
      DB_PORT: $DB_PORT

  telegram-service:
    build: ./telegram-service
    container_name: $TELEGRAM_APP_CONTAINER_NAME
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${TG_APP_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
